return {
  {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    opts = {
      bigfile = { enabled = true },
      dashboard = {
        enabled = true,
        preset = {
          header = "neovim 0.12  ·  bleeding edge",
          keys = {
            { icon = "f", key = "f", desc = "Find file", action = ":lua Snacks.picker.files()" },
            { icon = "n", key = "n", desc = "New file", action = ":ene | startinsert" },
            { icon = "g", key = "g", desc = "Grep", action = ":lua Snacks.picker.grep()" },
            { icon = "r", key = "r", desc = "Recent", action = ":lua Snacks.picker.recent()" },
            { icon = "s", key = "s", desc = "Session", action = ":lua require('persistence').load()" },
            { icon = "l", key = "l", desc = "Lazy", action = ":Lazy" },
            { icon = "q", key = "q", desc = "Quit", action = ":qa" },
          },
        },
      },
      explorer = { enabled = true },
      indent = { enabled = true },
      input = { enabled = true },
      notifier = { enabled = true, timeout = 3000 },
      picker = { enabled = true },
      quickfile = { enabled = true },
      scope = { enabled = true },
      scroll = { enabled = true },
      statuscolumn = { enabled = true },
      terminal = { enabled = true },
      words = { enabled = true },
      zen = { enabled = true },
      image = { enabled = true },
      dim = { enabled = true },
      git = { enabled = true },
      profiler = { enabled = true },
      animate = { enabled = true },
    },
    keys = {
      { "<leader><space>", function() Snacks.picker.files() end, desc = "Files" },
      { "<leader>ff", function() Snacks.picker.files() end, desc = "Files" },
      { "<leader>fg", function() Snacks.picker.git_files() end, desc = "Git files" },
      { "<leader>fr", function() Snacks.picker.recent() end, desc = "Recent files" },
      { "<leader>fb", function() Snacks.picker.buffers() end, desc = "Buffers" },
      { "<leader>/", function() Snacks.picker.grep() end, desc = "Grep" },
      { "<leader>sg", function() Snacks.picker.grep() end, desc = "Grep" },
      { "<leader>sw", function() Snacks.picker.grep_word() end, desc = "Grep word", mode = { "n", "x" } },
      { "<leader>sk", function() Snacks.picker.keymaps() end, desc = "Keymaps" },
      { "<leader>sh", function() Snacks.picker.help() end, desc = "Help" },
      { "<leader>ss", function() Snacks.picker.lsp_symbols() end, desc = "Document symbols" },
      { "<leader>sS", function() Snacks.picker.lsp_workspace_symbols() end, desc = "Workspace symbols" },
      { "<leader>sd", function() Snacks.picker.diagnostics() end, desc = "Diagnostics" },
      { "<leader>sD", function() Snacks.picker.diagnostics_buffer() end, desc = "Buffer diagnostics" },
      { "<leader>sc", function() Snacks.picker.commands() end, desc = "Commands" },
      { "<leader>sr", function() Snacks.picker.resume() end, desc = "Resume picker" },
      { "<leader>uC", function() Snacks.picker.colorschemes() end, desc = "Colorschemes" },
      { "<leader>e", function() Snacks.explorer() end, desc = "Explorer" },
      { "<leader>gg", function() Snacks.lazygit() end, desc = "Lazygit" },
      { "<leader>gb", function() Snacks.gitbrowse() end, desc = "Git browse", mode = { "n", "v" } },
      { "<leader>n", function() Snacks.notifier.show_history() end, desc = "Notifications" },
      { "<leader>un", function() Snacks.notifier.hide() end, desc = "Dismiss notifications" },
      { "<leader>z", function() Snacks.zen() end, desc = "Zen" },
      { "<leader>.", function() Snacks.scratch() end, desc = "Scratch" },
      { "<leader>S", function() Snacks.scratch.select() end, desc = "Scratch select" },
      { "<c-/>", function() Snacks.terminal() end, desc = "Terminal", mode = { "n", "t" } },
      { "<c-_>", function() Snacks.terminal() end, desc = "Terminal", mode = { "n", "t" } },
      { "]]", function() Snacks.words.jump(vim.v.count1) end, desc = "Next reference" },
      { "[[", function() Snacks.words.jump(-vim.v.count1) end, desc = "Prev reference" },
      { "<leader>up", function() Snacks.profiler.toggle() end, desc = "Profiler" },
      { "<leader>uP", function() Snacks.profiler.scratch() end, desc = "Profiler scratch" },
    },
  },
}
